// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCyyHI2rSYvsPfUc5pO6xkHExxIpkoaKM',
    appId: '1:636492327464:web:3f84a5dcd158358a49e31d',
    messagingSenderId: '636492327464',
    projectId: 'pc-relais-app',
    authDomain: 'pc-relais-app.firebaseapp.com',
    storageBucket: 'pc-relais-app.firebasestorage.app',
    measurementId: 'G-VEZPWPMXS1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCyyHI2rSYvsPfUc5pO6xkHExxIpkoaKM',
    appId: '1:636492327464:android:3f84a5dcd158358a49e31d',
    messagingSenderId: '636492327464',
    projectId: 'pc-relais-app',
    storageBucket: 'pc-relais-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCyyHI2rSYvsPfUc5pO6xkHExxIpkoaKM',
    appId: '1:636492327464:ios:3f84a5dcd158358a49e31d',
    messagingSenderId: '636492327464',
    projectId: 'pc-relais-app',
    storageBucket: 'pc-relais-app.firebasestorage.app',
    iosClientId: '636492327464-iosapp.apps.googleusercontent.com',
    iosBundleId: 'com.pcrelais.pcRelaisApp',
  );
}
